FROM maven:3.8-openjdk-17

RUN mkdir /tmp/build

COPY pom.xml /tmp/build
RUN cd /tmp/build && mvn dependency:resolve

COPY src /tmp/build/src

RUN cd /tmp/build && mvn -DskipTests=true package && \
    mv target/*.jar /app.jar \
    cd / && rm /tmp/build

